#!/bin/bash
scp weather_app.py pi@192.168.50.51:~/weather
scp weather_helper.py pi@192.168.50.51:~/weather
scp templates/current.html  pi@192.168.50.51:~/weather/templates/
scp templates/layout.html  pi@192.168.50.51:~/weather/templates/
scp index.php pi@192.168.50.51:/var/www/html/
scp config.php pi@192.168.50.51:~/weather
